=== eclipse-aspectj/aspectj/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test | comment)*>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >

   <!-- permits leading inc-compile, will fail -->
   <!ELEMENT ajc-test ((compile | inc-compile | run | weave | file | ant | comment)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >
   <!ATTLIST ajc-test vm CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,message*)>
   <!ATTLIST compile comment CDATA #IMPLIED >
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile badInput CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile reuseCompiler CDATA #IMPLIED >
   <!ATTLIST compile includeClassesDir CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile aspectsFiles CDATA #IMPLIED >
   <!ATTLIST compile classpath CDATA #IMPLIED >
   <!ATTLIST compile modulepath CDATA #IMPLIED >
   <!ATTLIST compile inpath CDATA #IMPLIED >
   <!ATTLIST compile extdirs CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >
   <!ATTLIST compile sourceroots CDATA #IMPLIED >
   <!ATTLIST compile xlintfile CDATA #IMPLIED >
   <!ATTLIST compile outjar CDATA #IMPLIED >
   <!ATTLIST compile outxmlfile CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >
   <!ATTLIST inc-compile fresh CDATA #IMPLIED >
   <!ATTLIST inc-compile checkModel CDATA #IMPLIED >

   <!ELEMENT run (dir-changes*,message*,stdout*,stderr*)>
   <!-- Either class or modulepath is required -->
   <!ATTLIST run class CDATA #IMPLIED >
   <!ATTLIST run modulepath CDATA #IMPLIED >
   <!ATTLIST run module CDATA #IMPLIED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >
   <!ATTLIST run errStreamIsError CDATA #IMPLIED >
   <!ATTLIST run outStreamIsError CDATA #IMPLIED >
   <!ATTLIST run fork CDATA #IMPLIED >
   <!ATTLIST run vmargs CDATA #IMPLIED >
   <!ATTLIST run aspectpath CDATA #IMPLIED >
   <!ATTLIST run classpath CDATA #IMPLIED >
   <!ATTLIST run ltw CDATA #IMPLIED >
   <!ATTLIST run usefullltw CDATA #IMPLIED >
   <!ATTLIST run exception CDATA #IMPLIED >
   <!ATTLIST run xlintfile CDATA #IMPLIED >

   <!ELEMENT message (source*)>
   <!ATTLIST message kind (abort | fail | error | warning | info | Xlint | weave) #IMPLIED >
   <!-- Java source code line; in weaving messages it denotes the weaving target, e.g. to where an advice is applied -->
   <!ATTLIST message line CDATA #IMPLIED >
   <!-- Aspect source code line; only useful for weaving messages where it denotes the source of what is woven in (e.g. advice) -->
   <!ATTLIST message aspectLine CDATA #IMPLIED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >
   <!ATTLIST message aspectFile CDATA #IMPLIED >
   <!ATTLIST message details CDATA #IMPLIED >

   <!ELEMENT source (#PCDATA)>
   <!ATTLIST source line CDATA #IMPLIED >
   <!ATTLIST source file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

   <!ELEMENT stdout (line*)>
   <!ATTLIST stdout ordered CDATA #IMPLIED >

   <!ELEMENT stderr (line*)>
   <!ATTLIST stderr ordered CDATA #IMPLIED >

   <!ELEMENT line (line*)>
   <!ATTLIST line text CDATA #REQUIRED >
   <!ATTLIST line vm CDATA #IMPLIED >

   <!ELEMENT weave (message*)>
   <!ATTLIST weave classesFiles CDATA #REQUIRED >
   <!ATTLIST weave aspectsFiles CDATA #REQUIRED >
   <!ATTLIST weave options CDATA #REQUIRED >
   <!ATTLIST weave xlintfile CDATA #IMPLIED >

   <!ELEMENT file EMPTY>
   <!ATTLIST file deletefile CDATA #IMPLIED >
   <!ATTLIST file renamefrom CDATA #IMPLIED >
   <!ATTLIST file renameto CDATA #IMPLIED >

   <!ELEMENT ant (stdout*,stderr*)>
   <!ATTLIST ant file CDATA #IMPLIED >
   <!ATTLIST ant target CDATA #IMPLIED >
   <!ATTLIST ant verbose CDATA #IMPLIED >

   <!ELEMENT comment (#PCDATA)>

=== eclipse-aspectj/aspectj/docs/modules/ROOT/pages/sandbox/ubc-design-patterns/patterns-test.xml
<!DOCTYPE suite SYSTEM "../../../tests/ajcTestSuite.dtd">

<!--
	To run with the harness, run 
	
	java org.aspectj.testing.drivers.Harness \
  	   ../docs/sandbox/ubc-design-patterns/patterns-test.xml -logFail	

	from a project directory (tests/ docs/ or testing-drivers)

	See tests/readme-writing-compiler-tests.html for more info on the harness.
-->
<suite>

	<ajc-test dir="src" 
		title="UBC design patterns library">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary" />
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns abstractFactory">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/abstractFactory/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns adapter">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/adapter/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns bridge">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/bridge/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns builder">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/builder/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns chainOfResponsibility">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/chainOfResponsibility/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns command">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/command/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns composite">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/composite/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns decorator">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/decorator/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns facade">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/facade/aspectj">
			<message kind="warning" line="72" />
		</compile>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns factoryMethod">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/factoryMethod/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns flyweight">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/flyweight/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns interpreter">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/interpreter/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns iterator">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/iterator/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns mediator">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/mediator/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns memento">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/memento/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns observer">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/observer/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns prototype">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/prototype/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns proxy">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/proxy/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns singleton">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/singleton/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns state">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/state/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns strategy">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/strategy/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns templateMethod">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/templateMethod/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns visitor">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/patternLibrary,ca/ubc/cs/spl/aspectPatterns/examples/visitor/aspectj"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java abstractFactory">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/abstractFactory/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java adapter">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/adapter/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java bridge">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/bridge/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java builder">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/builder/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java chainOfResponsibility">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/chainOfResponsibility/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java command">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/command/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java composite">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/composite/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java decorator">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/decorator/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java facade">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/facade/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java factoryMethod">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/factoryMethod/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java flyweight">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/flyweight/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java interpreter">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/interpreter/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java iterator">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/iterator/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java mediator">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/mediator/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java memento">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/memento/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java observer">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/observer/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java prototype">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/prototype/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java proxy">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/proxy/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java singleton">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/singleton/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java state">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/state/java"/>
	</ajc-test>

	<ajc-test dir="src" 
		title="UBC design patterns java strategy">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/strategy/java"/>
	</ajc-test>
	
	<ajc-test dir="src" 
		title="UBC design patterns java templateMethod">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/templateMethod/java"/>
	</ajc-test>
	
	<ajc-test dir="src" 
		title="UBC design patterns java visitor">
		<compile sourceroots="ca/ubc/cs/spl/aspectPatterns/examples/visitor/java"/>
	</ajc-test>

</suite>

=== eclipse-aspectj/aspectj/tests/src/test/resources/org/aspectj/systemtest/java14/java14.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>
<!-- Tests requiring JDK 1.4 or above -->
<suite>

  <ajc-test dir="pureJava" title="assert flow"
      keywords="from-14tests,purejava">
        <compile options="-source,1.4" files="AssertsCF.java">
            <message kind="error" line="8"/>
            <message kind="error" line="11"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" title="assert flow - 2"
      keywords="from-14tests,purejava">
        <compile options="-source,1.4" files="AssertsCF2.java">
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" title="assert typing"
      keywords="from-14tests,purejava,fail-publicType">
        <compile options="-source,1.4" files="AssertsCF1.java">
            <message kind="error" line="5"/>
        </compile>
    </ajc-test>

   <ajc-test dir="pureJava" title="compiling asserts in methods"
      keywords="from-14tests,purejava">
        <compile options="-source,1.4" files="AssertInMethod.java"/>
        <run class="AssertInMethod" vm="1.4"/>
    </ajc-test>

    <ajc-test dir="pureJava" title="asserts" keywords="from-14tests">
        <compile options="-source,1.4" files="Asserts.java"/>
        <run class="Asserts" vm="1.4"/>
    </ajc-test>
    
    <ajc-test dir="pureJava" pr="725"
      title="asserts in aspect and declared methods [requires 1.4]"
      keywords="from-14tests" comment="not pure java!">
        <compile options="-source,1.4"
          files="IntroducedAssertion.java"/>
        <run class="IntroducedAssertion" vm="1.4"/>
    </ajc-test>

    <!-- This test case requires bytecode generated according to the declaring type
        rules in JLS 2nd edition.  -1.4 must be passed to the eclipse compiler for
        this behavior. -->
    <ajc-test dir="new"
      title="Does the matrix coverage thing for the new method signatures"
      keywords="from-resolved_10x">
        <compile files="MethodSignatures.java" options="-1.4,-Xlint:ignore"/>
        <run class="MethodSignatures" vm="1.4"/>
    </ajc-test>  

    <!-- This test case requires bytecode generated according to the declaring type
        rules in JLS 2nd edition.  -1.4 must be passed to the eclipse compiler for
        this behavior. -->
    <ajc-test dir="new" title="correct types of parameters at call-sites"
      keywords="from-resolved_10x">
        <compile files="CallTypes.java" options="-1.4,-Xlint:ignore"/>
        <run class="CallTypes" vm="1.4"/>
    </ajc-test>

    <!-- This test case requires bytecode generated according to the declaring type
        rules in JLS 2nd edition.  -1.4 must be passed to the eclipse compiler for
        this behavior.  That means that this case will only work under 1.4.  -->
    <ajc-test dir="new"
      title="target type matching with messy interface hierarchies"
      keywords="from-resolved_10x">
        <compile files="CallTypesI.java" options="-1.4,-Xlint:ignore"/>
        <run class="CallTypesI" vm="1.4"/>
    </ajc-test>
 
      <ajc-test dir="new" title="assert tests in introduction [requires 1.4]"
      keywords="from-14tests,fail-unimplemented">
        <compile options="-source,1.4" files="AssertInIntro.java"/>
        <run class="AssertInIntro" vm="1.4"/>
    </ajc-test>

 
    <ajc-test dir="base/test131"
      title="various forms of package name pattern matching work"
      keywords="from-broken14usejavac">
        <compile files="Driver.java,p1/C1.java,p1/p2/C2.java" />
        <run class="Driver"/>
    </ajc-test>

     <ajc-test dir="new" pr="657"
      title="assert statement in advice coverage [requires 1.4]"
      keywords="from-14tests,fail-in-eclipse">
        <compile options="-source,1.4" files="AssertInAdvice.java"/>
        <run class="AssertInAdvice" vm="1.4"/>
    </ajc-test>

    <ajc-test dir="new" pr="657"
      title="assert statement in advice  [requires 1.4]" 
      keywords="from-14tests,fail-in-eclipse">
        <compile options="-source,1.4" files="AssertInAdviceBug.java"/>
        <run class="AssertInAdviceBug" vm="1.4"/>
    </ajc-test>

    <ajc-test dir="bugs" pr="28703" title="assert and pertarget crashes compiler">
        <compile files="EnsureOverriding.java" options="-source,1.4"/>
        <run class="EnsureOverriding" vm="1.4"/>
    </ajc-test>
    
    <ajc-test dir="bugs/interSpecials" title="testing that assert works like .class"
      pr="36110">
        <compile files="p1/C.java,p2/A2.java" options="-source,1.4"/>
        <run class="p2.A2" vm="1.4"/>
    </ajc-test>

   <ajc-test dir="bugs/jpOptimization" 
    	pr="45441"
    	title="JoinPoint Optimization when targetting 1.4">
        <compile 
        	files="de/test/MyMain.java,
        		   de/test/MyAspect.java"
            options="-1.4"/>
        <run class="de.test.MyMain"/>
    </ajc-test>

	<ajc-test dir="bugs"
		title="XLint warning for call PCD's using subtype of defining type (-1.4 -Xlint:ignore)"
		pr="41952"
		>
		<compile
			options="-Xlint:ignore,-1.4" 
			files="DeclaringTypeWarning.java" >
            <message kind="warning" line="12"/>
		</compile>
	</ajc-test>
	
	<ajc-test dir="bugs"
		title="XLint warning for call PCD's using subtype of defining type (-1.4)"
		pr="41952"
		>
		<compile
			options="-1.4" 
			files="DeclaringTypeWarning.java" >
			<message kind="warning" line="6" text="declaring type">
				<source line="14" file="DeclaringTypeWarning.java"/>
			</message>
			<message kind="warning" line="12" text="declare warning">
				<source line="19" file="DeclaringTypeWarning.java"/>
			</message>
		</compile>
	</ajc-test>
 
    <ajc-test dir="bugs" pr="39711"
   	 title="Class Literals as non final fields (also assert, and this$0)">
        <compile files="ClassLiteralField.java" options="-source,1.4"/>
        <run vm="1.4" class="ClassLiteralField"/>
    </ajc-test>
 

</suite>

=== eclipse-aspectj/aspectj/tests/src/test/resources/org/aspectj/systemtest/ajc164/declareMixin.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>

   <ajc-test dir="features164/declareMixin" title="casea">
     <compile files="CaseA.java" options="-1.5"/>
     <run class="CaseA">
       <stdout>
         <line text="Delegate factory invoked"/>
         <line text="methodOne running"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="caseb">
     <compile files="CaseB.java" options="-1.5"/>
     <run class="CaseB">
       <stdout>
         <line text="Delegate factory invoked"/>
         <line text="methodOne running"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casec">
     <compile files="CaseC.java" options="-1.5"/>
     <run class="CaseC">
       <stdout>
         <line text="Delegate factory invoked for CaseC instance"/>
         <line text="methodOne running"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="cased">
     <compile files="CaseD.java" options="-1.5"/>
     <run class="CaseD">
       <stdout>
         <line text="Delegate factory invoked for CaseD instance"/>
         <line text="methodOne running"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casee">
     <compile files="CaseE.java" options="-1.5"/>
     <run class="CaseE">
       <stdout>
         <line text="Delegate factory invoked for CaseE instance: a"/>
         <line text="methodOne running on CaseE instance: a"/>
         <line text="Delegate factory invoked for CaseE instance: b"/>
         <line text="methodTwo running on CaseE instance: b"/>
         <line text="methodOne running on CaseE instance: a"/>
         <line text="methodTwo running on CaseE instance: b"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casee_concurrent">
     <compile files="CaseEConcurrent.java" options="-1.5"/>
     <run class="CaseEConcurrent">
       <stdout ordered="no">
         <!--
           Without the concurrency fix from https://github.com/eclipse/org.aspectj/issues/198, each delegate factory
           would be invoked twice
         -->
         <line text="Delegate factory invoked for CaseEConcurrent instance: a"/>
         <line text="Delegate factory invoked for CaseEConcurrent instance: b"/>
         <line text="methodOne running on CaseEConcurrent instance: a"/>
         <line text="methodTwo running on CaseEConcurrent instance: a"/>
         <line text="methodOne running on CaseEConcurrent instance: b"/>
         <line text="methodTwo running on CaseEConcurrent instance: b"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casef">
     <compile files="CaseF.java" options="-1.5"/>
     <run class="CaseF">
       <stdout>
         <line text="Delegate factory invoked for CaseF instance"/>
         <line text="methodOne running"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="caseg">
     <compile files="CaseG.java" options="-1.5"/>
     <run class="CaseG">
       <stdout>
         <line text="Delegate factory invoked for instance of A"/>
         <line text="run() executing on behalf of A"/>
         <line text="Delegate factory invoked for instance of B"/>
         <line text="run() executing on behalf of B"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="caseh">
     <compile files="CaseH.java" options="-1.5">
         <message kind="error" text="The value for annotation attribute DeclareMixin"/>
     </compile>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casei">
     <compile files="CaseI.java" options="-1.5">
         <message kind="error" text="Types listed in the 'interfaces'"/>
     </compile>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casej">
     <compile files="CaseJ.java" options="-1.5">
         <message kind="error" text="createImplementation1"/>
         <message kind="error" text="Method 'int X.createImplementation2(java.lang.Object)':  factory methods "/>
     </compile>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casek">
     <compile files="CaseK.java" options="-1.5">
         <message kind="error" text="factory methods for a mixin can take a maximum of one parameter"/>
     </compile>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casel">
     <compile files="CaseL.java" options="-1.5">
       <message kind="error" text="Cannot cast from CaseL to C"/>
     </compile>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casem">
     <compile files="CaseM.java" options="-1.5">
       <message kind="error" text=": factory methods for a mixin must either return an interface type or specify interfaces in the annotation and return a class"/>
     </compile>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casen">
     <compile files="CaseN.java" options="-1.5"/>
     <run class="CaseN">
       <stdout>
         <line text="foo() running"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="caseo">
     <compile files="CaseO.java" options="-1.5">
       <message kind="error" text="factory method does not return something that implements 'I'"/>
     </compile>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="casep">
     <compile files="CaseP.java" options="-1.5"/>
     <run class="CaseP">
       <stdout>
         <line text="foo() running"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="caseq">
     <compile files="CaseQ.java" options="-1.5"/>
     <run class="CaseQ">
       <stdout>
         <line text="foo() running"/>
         <line text="goo() running"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="caser">
     <compile files="CaseR.java" options="-1.5"/>
     <run class="CaseR">
       <stdout>
         <line text="true"/>
         <line text="false"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="cases">
     <compile files="CaseS.java" options="-1.5">
       <message kind="error" text="not compatible"/>
     </compile>
   </ajc-test>

   <ajc-test dir="features164/declareMixin" title="caset">
     <compile files="CaseT.java" options="-1.5 -showWeaveInfo">
       <message kind="weave" text="Mixing interface 'I' (CaseT.java) into type 'CaseT' (CaseT.java)"/>
     </compile>
   </ajc-test>
</suite>
