=== eclipse-aspectj/aspectj/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test | comment)*>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >

   <!-- permits leading inc-compile, will fail -->
   <!ELEMENT ajc-test ((compile | inc-compile | run | weave | file | ant | comment)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >
   <!ATTLIST ajc-test vm CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,message*)>
   <!ATTLIST compile comment CDATA #IMPLIED >
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile badInput CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile reuseCompiler CDATA #IMPLIED >
   <!ATTLIST compile includeClassesDir CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile aspectsFiles CDATA #IMPLIED >
   <!ATTLIST compile classpath CDATA #IMPLIED >
   <!ATTLIST compile modulepath CDATA #IMPLIED >
   <!ATTLIST compile inpath CDATA #IMPLIED >
   <!ATTLIST compile extdirs CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >
   <!ATTLIST compile sourceroots CDATA #IMPLIED >
   <!ATTLIST compile xlintfile CDATA #IMPLIED >
   <!ATTLIST compile outjar CDATA #IMPLIED >
   <!ATTLIST compile outxmlfile CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >
   <!ATTLIST inc-compile fresh CDATA #IMPLIED >
   <!ATTLIST inc-compile checkModel CDATA #IMPLIED >

   <!ELEMENT run (dir-changes*,message*,stdout*,stderr*)>
   <!-- Either class or modulepath is required -->
   <!ATTLIST run class CDATA #IMPLIED >
   <!ATTLIST run modulepath CDATA #IMPLIED >
   <!ATTLIST run module CDATA #IMPLIED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >
   <!ATTLIST run errStreamIsError CDATA #IMPLIED >
   <!ATTLIST run outStreamIsError CDATA #IMPLIED >
   <!ATTLIST run fork CDATA #IMPLIED >
   <!ATTLIST run vmargs CDATA #IMPLIED >
   <!ATTLIST run aspectpath CDATA #IMPLIED >
   <!ATTLIST run classpath CDATA #IMPLIED >
   <!ATTLIST run ltw CDATA #IMPLIED >
   <!ATTLIST run usefullltw CDATA #IMPLIED >
   <!ATTLIST run exception CDATA #IMPLIED >
   <!ATTLIST run xlintfile CDATA #IMPLIED >

   <!ELEMENT message (source*)>
   <!ATTLIST message kind (abort | fail | error | warning | info | Xlint | weave) #IMPLIED >
   <!-- Java source code line; in weaving messages it denotes the weaving target, e.g. to where an advice is applied -->
   <!ATTLIST message line CDATA #IMPLIED >
   <!-- Aspect source code line; only useful for weaving messages where it denotes the source of what is woven in (e.g. advice) -->
   <!ATTLIST message aspectLine CDATA #IMPLIED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >
   <!ATTLIST message aspectFile CDATA #IMPLIED >
   <!ATTLIST message details CDATA #IMPLIED >

   <!ELEMENT source (#PCDATA)>
   <!ATTLIST source line CDATA #IMPLIED >
   <!ATTLIST source file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

   <!ELEMENT stdout (line*)>
   <!ATTLIST stdout ordered CDATA #IMPLIED >

   <!ELEMENT stderr (line*)>
   <!ATTLIST stderr ordered CDATA #IMPLIED >

   <!ELEMENT line (line*)>
   <!ATTLIST line text CDATA #REQUIRED >
   <!ATTLIST line vm CDATA #IMPLIED >

   <!ELEMENT weave (message*)>
   <!ATTLIST weave classesFiles CDATA #REQUIRED >
   <!ATTLIST weave aspectsFiles CDATA #REQUIRED >
   <!ATTLIST weave options CDATA #REQUIRED >
   <!ATTLIST weave xlintfile CDATA #IMPLIED >

   <!ELEMENT file EMPTY>
   <!ATTLIST file deletefile CDATA #IMPLIED >
   <!ATTLIST file renamefrom CDATA #IMPLIED >
   <!ATTLIST file renameto CDATA #IMPLIED >

   <!ELEMENT ant (stdout*,stderr*)>
   <!ATTLIST ant file CDATA #IMPLIED >
   <!ATTLIST ant target CDATA #IMPLIED >
   <!ATTLIST ant verbose CDATA #IMPLIED >

   <!ELEMENT comment (#PCDATA)>

=== eclipse-aspectj/aspectj/tests/src/test/resources/org/aspectj/systemtest/ajc160/ajc160.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.6.0 Tests -->
<suite>

    <ajc-test dir="bugs160/pr226567" title="pipeline compilation and generic return type">
        <compile files="BarAspect.aj Foo.java Bar.java" options="-1.5"/>
        <compile files="BarAspect.aj Bar.java Foo.java" options="-1.5"/>
    </ajc-test>

	<ajc-test dir="bugs160/pr225916" title="pipeline compilation and anonymous type">
		<compile files="Test.java TestMBean.java TestAspect.java" options="-showWeaveInfo">
		 <message kind="weave" text="Join point 'method-execution(java.lang.String test.jmx.Test.test())' in Type"/>
		</compile>
	</ajc-test>

	<ajc-test dir="bugs160/pr214994" title="generic itd">
		<compile files="Broke.java" options="-1.5"/>
	</ajc-test>

	<ajc-test dir="bugs160/pr223605" title="generic decp ltw">
		<compile files="GenericConfigurableBugTest.java" options="-1.5"><!-- -showWeaveInfo"-->
		</compile>
		<run class="test.GenericConfigurableBugTest"/>
	</ajc-test>

	<ajc-test dir="bugs160/pr173602" title="duplicate itd npe">
		<compile files="X.java">
		  <message kind="error" line="2" text="intertype declaration from "/>
		  <message kind="error" line="3" text="intertype declaration from "/>
		  <message kind="error" line="6" text="intertype declaration from "/>
		</compile>
	</ajc-test>
	
    <ajc-test dir="bugs160/pr223094" title="ltw inherited itds">
      <compile files="B.java" outjar="foo.jar"/>
      <compile files="A.java" classpath="$sandbox/foo.jar"/>
      <run class="p.A" classpath="$sandbox/foo.jar" ltw="aop.xml">
        <stdout>
          <line text="ok"/>
 	    </stdout>
      </run>
    </ajc-test>

   <ajc-test dir="bugs160/pr167197" title="generic type parameterized with array type">
     <compile options="-1.5" files="AspectBreaker.java"/>
   </ajc-test>
   
   <ajc-test dir="bugs160/pr167197" title="generic type parameterized with array type - 2">
     <compile options="-1.5" files="Breaker2.java"/>
     <run class="Breaker2"/>
   </ajc-test>
   
   <ajc-test dir="bugs160/pr180264" title="classcastexception on array type">
     <compile options="-warn:+uselessTypeCheck" files="Foo.java,Main.java"/>
   </ajc-test>
   
	<ajc-test dir="bugs160/pr145018" title="ataj crashing with cflow, if and args">
     <compile files="Broken.aj" options="-1.5"/>
     <run class="Broken">
     </run>
    </ajc-test> 
    
	<ajc-test dir="bugs160/pr201748" title="itd with array">
     <compile files="Foo.java">
       <message kind="error" text="Type mismatch: cannot convert from Factory[] to Factory"/>
     </compile>
   </ajc-test>
   
   <ajc-test dir="bugs160/various" title="incorrect itd error with generics">
     <compile options="-1.5 -showWeaveInfo" files="IncorrectMessage.java">
       <message kind="weave" text="Type 'Foo' (IncorrectMessage.java) has intertyped method from 'AspectDoWhatEver' (IncorrectMessage.java:'void Marker.doWhatEver()')"/>
       <message kind="weave" text="Type 'Marker' (IncorrectMessage.java) has intertyped method from 'AspectDoWhatEver' (IncorrectMessage.java:'void Marker.doWhatEver()')"/>
     </compile>       
   </ajc-test>
   
   <ajc-test dir="bugs160/various" title="incorrect itd error with generics - 2">
     <compile options="-1.5 -showWeaveInfo" files="IncorrectMessage2.java">
       <message kind="weave" text="Type 'Foo' (IncorrectMessage2.java) has intertyped method from 'AspectDoWhatEver' (IncorrectMessage2.java:'void Marker.doWhatEver()')"/>
       <message kind="weave" text="Type 'Marker' (IncorrectMessage2.java) has intertyped method from 'AspectDoWhatEver' (IncorrectMessage2.java:'void Marker.doWhatEver()')"/>
     </compile>       
   </ajc-test>
   
   
   <ajc-test dir="bugs160/various" title="hasmethod anno value - I">
     <compile options="-1.5 -XhasMember -showWeaveInfo" files="A.java">
       <message kind="weave" text="Extending interface set for type 'B' (A.java) to include 'java.io.Serializable' (A.java)"/>
     </compile>
   </ajc-test>

   <ajc-test dir="bugs160/various" title="hasmethod anno value - Z">
     <compile options="-1.5 -XhasMember -showWeaveInfo" files="Z.java">
       <message kind="weave" text="Extending interface set for type 'B' (Z.java) to include 'java.io.Serializable' (Z.java)"/>
     </compile>
   </ajc-test>
   
   <ajc-test dir="bugs160/various" title="hasmethod anno value - S">
     <compile options="-1.5 -XhasMember -showWeaveInfo" files="S.java">
       <message kind="weave" text="Extending interface set for type 'B' (S.java) to include 'java.io.Serializable' (S.java)"/>
     </compile>
   </ajc-test>

   <ajc-test dir="bugs160/various" title="hasmethod semantics">
     <compile options="-1.5 -XhasMember -Xlint:ignore" files="HasMethodSemantics.java"/>
     <run class="HasMethodSemantics">
       <stdout>
         <line text="Implements Marker? no"/>
       </stdout>
     </run>
   </ajc-test>

   <ajc-test dir="bugs160/pr204505" title="generics method matching - 1">
     <compile options="-1.5 -showWeaveInfo" files="Bug.java">
       <message kind="weave" text="execution(void C.save(java.lang.Object))"/>
       <message kind="weave" text="execution(void C.saveAll(java.util.Collection))"/>
     </compile>
   </ajc-test>

   <ajc-test dir="bugs160/pr204505" title="generics method matching - 2">
     <compile options="-1.5" files="GenericInterfaceWithGenericArgumentPointcutBug.java"/>
     <run class="mypackage.GenericInterfaceWithGenericArgumentPointcutBug"/>
   </ajc-test>  
   
   <ajc-test dir="bugs160/pr219298" title="bounds check failure">
     <compile options="-1.5" files="TestMarkers.java">
       <message kind="error" line="11" text="Bound mismatch: The type TestMarkers.SubGenericsType is not a valid substitute for the bounded"/>
     </compile>
   </ajc-test>

   <ajc-test dir="bugs160/pr219298" title="bounds check failure - 2">
     <compile options="-1.5" files="TestMarkers2.java"/>
   </ajc-test>

   <ajc-test dir="bugs160/pr218167" title="dec field problem">
     <compile options="-1.5" files="Test.java">
       <message kind="warning" text="already has an annotation of type A, cannot add a second instance"/>
     </compile>
   </ajc-test>

   <ajc-test dir="bugs160/pr206911" title="generics super itd">
     <compile options="-1.5" files="VerifyError.java"/>
     <run class="bugs.VerifyError"/>
   </ajc-test>

   <ajc-test dir="bugs160/pr206911" title="generics super itd - 2">
     <compile options="-1.5" files="VerifyError2.java"/>
     <run class="bugs.VerifyError2"/>
   </ajc-test>
   
   <ajc-test dir="bugs160/pr216311" title="serialization and annotation style">
     <compile options="-1.5" files="PersistabilityTest.java,IPersistable.java,Persistability.java"/>
     <run class="PersistabilityTest"/>
   </ajc-test>

   <ajc-test dir="bugs160/pr214559" title="decp repetition problem">
     <compile files="X.java"/>
     <run class="test.X"/>
   </ajc-test>
   
   <ajc-test dir="bugs160/pr214559" title="decp repetition problem - 2">
     <compile files="Y.java"/>
     <run class="Y"/>
   </ajc-test>

   <ajc-test dir="bugs160/pr214559" title="decp repetition problem - 3">
     <compile files="TestClass.java Interface1.java Interface1TestClass.java DeclareParentsPrecedenceTest.java TestAspect.java"/>
     <run class="DeclareParentsPrecedenceTest"/>
   </ajc-test>

   <ajc-test dir="bugs160/pr209831" title="illegal state exception with annotations">
     <compile options="-1.5 -showWeaveInfo" files="Test.java">
       <message kind="weave" text="Join point 'exception-handler(void Test.&lt;catch&gt;(java.lang.Throwable))' in Type 'Test' (Test.java:34) advised by before advice from 'ExactAnnotationTypePatternBug' (Test.java:5)"/>
     </compile>
     <run class="Test"/>
   </ajc-test>

   <ajc-test dir="bugs160/pr209831" title="illegal state exception with annotations - 2">
     <compile options="-Xlint:ignore -1.5 -showWeaveInfo" files="Test2.java"/>
     <run class="Test2"/>
   </ajc-test>
   
   <ajc-test dir="bugs160/pr211146" title="itd lost generic signature">
     <compile options=" -1.5" files="StringAspect.aj,StringClass.java" outjar="foo.jar"/>
     <compile options=" -1.5" files="DemoUsage.java" classpath="foo.jar"/>
   </ajc-test>
   
</suite>

=== eclipse-aspectj/aspectj/docs/modules/ROOT/pages/sandbox/sandbox-api-test.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">
<!-- ../ path when running, ../../ when editing? -->


<!-- 
	This is just like sandbox-test.xml except that it is
	reserved for code that uses the AspectJ API's because
	it assumes the build has created the target library,
	
	   ../aj-build/dist/tools/lib/aspectjtools.jar
	
	and that we run from a peer directory of this one.
-->
<suite>
		
	<ajc-test dir="api-clients" title="api-ajde-modelWalker"
		comment="BROKEN - function unvalidated, only that it compiles and runs">
		<compile files="org/aspectj/samples/JoinPointCollector.java"
			classpath="../../../aj-build/dist/tools/lib/aspectjtools.jar"/>
		<run class="org/aspectj/samples/JoinPointCollector"
			options="-help"/>
		</ajc-test>

	<ajc-test dir="api-clients" title="api-asm-listAffectedFiles"
		comment="function unvalidated; note run paths are relative to harness cwd">
		<compile files="org/aspectj/samples/AffectedFilesReporter.java"
			classpath="../../../aj-build/dist/tools/lib/aspectjtools.jar"/>
		<run class="org/aspectj/samples/AffectedFilesReporter"
            outStreamIsError="true"
			options="-emacssym,@../aj-build/dist/docs/doc/examples/tracing/notrace.lst"/>
		<run class="org/aspectj/samples/AffectedFilesReporter"
			options="-emacssym,@../aj-build/dist/docs/doc/examples/tracing/tracev3.lst"/>
		</ajc-test>
</suite>

=== eclipse-aspectj/aspectj/tests/src/test/resources/org/aspectj/systemtest/ajc190/ajc190.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>


  <ajc-test dir="bugs190/paramannos" title="param annos negative">
    <compile files="Code.java" options="-1.9 -showWeaveInfo">
    		<message kind="weave" text="Join point 'constructor-execution(void Code.&lt;init&gt;(java.lang.Object))' in Type 'Code' (Code.java:8) advised by before advice from 'X' (Code.java:12)"/>
	</compile>
  </ajc-test>


  <ajc-test dir="bugs190/modules/aaa" title="build a module">
    <compile files="module-info.java com/foo1/C1.java" options="-1.9"/>
  </ajc-test>

  <ajc-test dir="bugs190/modules/bbb" title="run a module - classpath">
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9"/>
    <run class="aaa.bbb.A">
    <stdout>
    <line text="A running"/>
    </stdout>
    </run>
  </ajc-test>

  <ajc-test dir="bugs190/modules/bbb" title="run a module - modulepath">
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9"/>
    <run modulepath="$sandbox" module="my.module/aaa.bbb.A">
    <stdout>
    <line text="A running"/>
    </stdout>
    </run>
  </ajc-test>
  
  <ajc-test dir="bugs190/modules/bbb" title="package and run a module - modulepath">
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="my.module.jar"/>
   	<file deletefile="module-info.java"/>
    <file deletefile="aaa"/>
    <run modulepath="my.module.jar" module="my.module/aaa.bbb.A">
    <stdout>
    <line text="A running"/>
    </stdout>
    </run>
   </ajc-test>
  
  <ajc-test dir="bugs190/modules/ccc" title="compile regular code using module code">
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="modules/my.module.jar"/>
    <file deletefile="module-info.java"/>
    <file deletefile="aaa"/>
    <compile files="InvokeA.java" options="-1.9" modulepath="$sandbox/modules/my.module.jar"/>
  </ajc-test>
  
  <ajc-test dir="bugs190/modules/ddd" title="compile regular code using module code that isn't visible">
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="modules/my.module.jar"/>
    <compile files="InvokeA.java" options="-1.9" modulepath="$sandbox/modules/my.module.jar">
		<message kind="error" text="package aaa.bbb is not visible"/>
    </compile>
  </ajc-test>


  <ajc-test dir="bugs190/modules/eee" title="binary weaving module">
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="my.module.jar"/>
    <file deletefile="module-info.java"/>
    <file deletefile="aaa"/>
    <compile files="Azpect.java" inpath="my.module.jar" outjar="my.module.woven.jar"/>
    <run modulepath="my.module.woven.jar" module="my.module/aaa.bbb.A">
      <stdout>
      <line text="Azpect running"/>
      <line text="A running"/>
      </stdout>
    </run>
  </ajc-test>


  <ajc-test dir="bugs190/520135" title="funny signature with method reference">
    <compile files="FailsApectJ.java" options="-1.8"/>
  </ajc-test>

  <ajc-test dir="bugs190/modules/fff" title="compile module including aspects">
    <compile files="module-info.java pkg/Demo.java otherpkg/Azpect.java" modulepath="$runtimemodule" outjar="demomodule.jar" options="-1.9"/>
    <run modulepath="$runtimemodule:demomodule.jar" module="demo/pkg.Demo">
      <stdout>
      <line text="Azpect running"/>
      <line text="Demo running"/>
      </stdout>
    </run>
  </ajc-test>
  
  <ajc-test dir="bugs190/modules/eee" title="compile module and apply aspects via aspectpath">
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="my.module.jar"/>
    <file deletefile="module-info.java"/>
    <file deletefile="aaa"/>
    <compile files="Azpect.java" outjar="azpects.jar" options="-1.4"/>
    <compile options="-showWeaveInfo" inpath="my.module.jar" aspectpath="azpects.jar" outjar="my.module.woven.jar">
    		<message kind="weave" text="Join point 'method-execution(void aaa.bbb.A.main(java.lang.String[]))' in Type 'aaa.bbb.A' (A.java:4) advised by before advice from 'aspects.Azpect' (azpects.jar!Azpect.class:4(from Azpect.java))"/>    
    </compile>
    <file deletefile="my.module.jar"/>
    <run classpath="my.module.woven.jar:azpects.jar" class="aaa.bbb.A">
      <stdout>
      <line text="Azpect running"/>
      <line text="A running"/>
      </stdout>
    </run>
  </ajc-test>
  
  <ajc-test dir="bugs190/modules/ggg" title="module path vs classpath 1">
    <!-- build some simple code into a jar we can depend on *not a module* -->
    <compile files="ddd/D.java" options="-1.9" outjar="foo.jar"/>
    <file deletefile="ddd/D.java"/>
    <!-- compile a module that depends on that -->
    <!-- this fails because if you start working with modules you commit to the modules story and classpath
         becomes irrelevant -->
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="module.jar" classpath="foo.jar">
    <message kind="error" text="The type ddd.D is not accessible"/>
    <message kind="error" text="D cannot be resolved"/>
    <!-- 
    <message kind="error" text="The import ddd cannot be resolved"/>
    <message kind="error" text="package ddd is not visible"/>
     -->
    </compile>
  </ajc-test>
  
  <ajc-test dir="bugs190/modules/hhh" title="module path vs classpath 2">
    <!-- build some simple code into a jar we can depend on *not a module* -->
    <file renamefrom="module-info-a.java" renameto="module-info.java"/>
    <compile files="module-info.java ddd/D.java" options="-1.9" outjar="my.module.a.jar"/>
    <!-- 
    <file renamefrom="module-info-b.java" renameto="module-info.java"/>
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="my.module.b.jar" modulepath="my.module.a.jar"/>
     -->
  </ajc-test>
  
  <ajc-test dir="bugs190/modules/iii" title="compile use of java.xml.bind">
    <compile files="UsesJAXB.java" options="--add-modules java.xml.bind -1.9"/>
    <run class="UsesJAXB" vmargs="--add-modules java.xml.bind">
      <stdout>
      <line text="UsesJAXB.running..."/>
      </stdout>
    </run>
  </ajc-test>
    
  <ajc-test dir="bugs190/modules/iii" title="weave use of java.xml.bind">
    <compile files="UsesJAXB.java Azpect.java" options="--add-modules java.xml.bind -1.9"/>
    <run class="UsesJAXB" vmargs="--add-modules java.xml.bind">
      <stdout>
      <line text="UsesJAXB.running..."/>
      <line text="null"/>
      </stdout>
    </run>
  </ajc-test>
  
  <ajc-test dir="bugs190/modules/iii" title="limit modules 1">
    <compile files="UsesJAXB.java Azpect.java" options="--limit-modules java.xml.bind -1.9"/>
    <run class="UsesJAXB" vmargs="--limit-modules java.xml.bind">
      <stdout>
      <line text="UsesJAXB.running..."/>
      <line text="null"/>
      </stdout>
    </run>
  </ajc-test>
  
  <ajc-test dir="bugs190/modules/iii" title="add reads 1">
    <compile files="UsesJAXB.java Azpect.java" options="--add-reads java.sql=java.xml.bind --add-modules java.sql -1.9"/>
    <run class="UsesJAXB" vmargs="--add-modules java.xml.bind ">
      <stdout>
      <line text="UsesJAXB.running..."/>
      <line text="null"/>
      </stdout>
    </run>
  </ajc-test>
  
  <!-- 
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="module.jar" aspectpath="foo.jar"/>
    <compile files="module-info.java aaa/bbb/A.java" options="-1.9" outjar="my.module.jar"/>
    <file deletefile="module-info.java"/>
    <file deletefile="aaa"/>
    <compile files="Azpect.java" outjar="azpects.jar"/>
    <compile options="-showWeaveInfo" inpath="my.module.jar" aspectpath="azpects.jar" outjar="my.module.woven.jar">
    		<message kind="weave" text="Join point 'method-execution(void aaa.bbb.A.main(java.lang.String[]))' in Type 'aaa.bbb.A' (A.java:4) advised by before advice from 'aspects.Azpect' (azpects.jar!Azpect.class:4(from Azpect.java))"/>    
    </compile>
    <file deletefile="my.module.jar"/>
    <run classpath="my.module.woven.jar:azpects.jar" class="aaa.bbb.A">
      <stdout>
      <line text="Azpect running"/>
      <line text="A running"/>
      </stdout>
    </run>
  </ajc-test>
     -->
  
  <ajc-test dir="bugs190/modules" title="weave module">
    <compile files="aspect1/Azpect1.java" inpath="module1/module-one.jar" outjar="runner.jar" options="-1.8"/>
    <java classpath="runner.jar" class="a.b.c.Code"/>
  </ajc-test>
  
  <ajc-test dir="bugs190/various" title="setting static final outside clinit">
	  <compile files="Code.java" options="-1.9"/>
	  <run class="Code">
	  <stdout>
	  <line text="call(void java.io.PrintStream.println(String))"/>
	  <line text="running"/>
	  </stdout>
	  </run>
  </ajc-test>

	<!-- from ajc153 -->
    <ajc-test dir="bugs153/pr156962" title="Test Annot Method Has Member 1">
      <compile files="Sample.java, LiftDeprecation.aj" options="-1.9 -XhasMember -showWeaveInfo -Xlint:ignore">
        <message kind="weave" text="'Sample' (Sample.java:1) is annotated with @Deprecated type annotation from 'LiftDeprecation' (LiftDeprecation.aj:2)"/>
      </compile>
    </ajc-test>

	<!-- from ajc153 -->
    <ajc-test dir="bugs153/pr156962" title="Test Annot Method Has Member 2">
      <compile files="Sample.java, LiftDeprecation.aj" options="-1.8 -XhasMember -showWeaveInfo -Xlint:ignore">
        <message kind="weave" text="'Sample' (Sample.java:1) is annotated with @Deprecated type annotation from 'LiftDeprecation' (LiftDeprecation.aj:2)"/>
      </compile>
    </ajc-test>

</suite>

=== eclipse-aspectj/aspectj/tests/src/test/resources/org/aspectj/systemtest/tracing/tracing.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- Tracing Tests -->
<suite>

	<ajc-test dir="tracing" title="Tracing" keywords="tracing">
        <compile
        	files="TracingTest.java"
        />
        <ant file="ant.xml" target="Tracing" verbose="true">
        	<stdout>
                <line text="? TracingTest.main() trace="/>
            </stdout>
		</ant>      
    </ajc-test>

	<ajc-test dir="tracing" title="Default tracing" keywords="tracing">
        <compile
        	files="DefaultTracingTest.java"
        />
        <ant file="ant.xml" target="Default tracing" verbose="true">
        	<stdout>
                <line text="? DefaultTracingTest.main() trace=org.aspectj.weaver.tools.DefaultTrace"/>
            </stdout>
		</ant>        
    </ajc-test>

	<ajc-test dir="tracing" title="Trace messages" keywords="tracing">
        <compile
        	files="HelloWorld.java"
        />
        <compile
        	files="IncludedAspect.aj, ExcludedAspect.aj"
        />
		<ant file="ant.xml" target="Trace messages" verbose="true">
        	<stdout>
                <line text="Hello World!"/>
            </stdout>
            <!-- 
            	Always get info messages even without -verbose because output determined
                by tracing infrastructure.
                 
                Duplicate warning and error messages: first through trace then message 
                writer
            -->
        	<stderr>
        		<line text="WARNING: A terminally deprecated method in sun.misc.Unsafe has been called" vm="24"/>
        		<line text="WARNING: sun.misc.Unsafe::objectFieldOffset has been called by org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor" vm="24"/>
        		<line text="WARNING: Please consider reporting this to the maintainers of class org.aspectj.weaver.loadtime.ClassLoaderWeavingAdaptor" vm="24"/>
        		<line text="WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release" vm="24"/>
	  	    	<line text="info AspectJ Weaver Version"/>
	  	    	<line text="info register classloader"/>
	  	    	<line text="info using configuration"/>
	  	    	<line text="info register aspect IncludedAspect"/>
	  	    	<line text="warning aspect ExcludedAspect exluded"/>
	  	    	<line text="warning aspect ExcludedAspect exluded"/>
	  	    	<line text="info define aspect IncludedMissingAspect"/>
	  	    	<line text="error Cannot find parent aspect"/>
	  	    	<line text="error Cannot find parent aspect"/>
	  	    	<line text="error Concrete-aspect 'IncludedMissingAspect' could not be registered"/>
	  	    	<line text="error Concrete-aspect 'IncludedMissingAspect' could not be registered"/>
	  	    	<line text="warning failure(s) registering aspects. Disabling weaver for class loader"/>
	  	    	<line text="warning failure(s) registering aspects. Disabling weaver for class loader"/>
            </stderr>
        </ant>
    </ajc-test>

	<ajc-test dir="tracing" title="Trace everything" keywords="tracing">
        <compile
        	files="HelloWorld.java"
        />
        <compile files="Aspect.aj" options="-outxml -1.8 -Xlint:ignore"/>
		<ant file="ant.xml" target="Trace everything" verbose="true">
        	<stdout>
                <line text="Hello World!"/>
            </stdout>
        </ant>
    </ajc-test>

	<ajc-test dir="tracing" title="JDK 1.4 tracing" keywords="tracing">
        <compile
        	files="HelloWorld.java"
        />
        <compile files="Aspect.aj" options="-outxml -1.8 -Xlint:ignore"/>
		<ant file="ant.xml" target="JDK 1.4 tracing" verbose="true">
        	<stdout>
                <line text="Hello World!"/>
            </stdout>
        </ant>
    </ajc-test>

	<ajc-test dir="tracing" title="Tracing file System Property" keywords="tracing">
        <compile files="HelloWorld.java"/>
        <compile files="Aspect.aj" options="-outxml -1.8 -Xlint:ignore"/>
		<ant file="ant.xml" target="Tracing file System Property" verbose="true">
        	<stdout>
                <line text="Hello World!"/>
            </stdout>
        </ant>
    </ajc-test>
</suite>
