=== eclipse-aspectj/aspectj/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test | comment)*>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >

   <!-- permits leading inc-compile, will fail -->
   <!ELEMENT ajc-test ((compile | inc-compile | run | weave | file | ant | comment)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >
   <!ATTLIST ajc-test vm CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,message*)>
   <!ATTLIST compile comment CDATA #IMPLIED >
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile badInput CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile reuseCompiler CDATA #IMPLIED >
   <!ATTLIST compile includeClassesDir CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile aspectsFiles CDATA #IMPLIED >
   <!ATTLIST compile classpath CDATA #IMPLIED >
   <!ATTLIST compile modulepath CDATA #IMPLIED >
   <!ATTLIST compile inpath CDATA #IMPLIED >
   <!ATTLIST compile extdirs CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >
   <!ATTLIST compile sourceroots CDATA #IMPLIED >
   <!ATTLIST compile xlintfile CDATA #IMPLIED >
   <!ATTLIST compile outjar CDATA #IMPLIED >
   <!ATTLIST compile outxmlfile CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >
   <!ATTLIST inc-compile fresh CDATA #IMPLIED >
   <!ATTLIST inc-compile checkModel CDATA #IMPLIED >

   <!ELEMENT run (dir-changes*,message*,stdout*,stderr*)>
   <!-- Either class or modulepath is required -->
   <!ATTLIST run class CDATA #IMPLIED >
   <!ATTLIST run modulepath CDATA #IMPLIED >
   <!ATTLIST run module CDATA #IMPLIED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >
   <!ATTLIST run errStreamIsError CDATA #IMPLIED >
   <!ATTLIST run outStreamIsError CDATA #IMPLIED >
   <!ATTLIST run fork CDATA #IMPLIED >
   <!ATTLIST run vmargs CDATA #IMPLIED >
   <!ATTLIST run aspectpath CDATA #IMPLIED >
   <!ATTLIST run classpath CDATA #IMPLIED >
   <!ATTLIST run ltw CDATA #IMPLIED >
   <!ATTLIST run usefullltw CDATA #IMPLIED >
   <!ATTLIST run exception CDATA #IMPLIED >
   <!ATTLIST run xlintfile CDATA #IMPLIED >

   <!ELEMENT message (source*)>
   <!ATTLIST message kind (abort | fail | error | warning | info | Xlint | weave) #IMPLIED >
   <!-- Java source code line; in weaving messages it denotes the weaving target, e.g. to where an advice is applied -->
   <!ATTLIST message line CDATA #IMPLIED >
   <!-- Aspect source code line; only useful for weaving messages where it denotes the source of what is woven in (e.g. advice) -->
   <!ATTLIST message aspectLine CDATA #IMPLIED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >
   <!ATTLIST message aspectFile CDATA #IMPLIED >
   <!ATTLIST message details CDATA #IMPLIED >

   <!ELEMENT source (#PCDATA)>
   <!ATTLIST source line CDATA #IMPLIED >
   <!ATTLIST source file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

   <!ELEMENT stdout (line*)>
   <!ATTLIST stdout ordered CDATA #IMPLIED >

   <!ELEMENT stderr (line*)>
   <!ATTLIST stderr ordered CDATA #IMPLIED >

   <!ELEMENT line (line*)>
   <!ATTLIST line text CDATA #REQUIRED >
   <!ATTLIST line vm CDATA #IMPLIED >

   <!ELEMENT weave (message*)>
   <!ATTLIST weave classesFiles CDATA #REQUIRED >
   <!ATTLIST weave aspectsFiles CDATA #REQUIRED >
   <!ATTLIST weave options CDATA #REQUIRED >
   <!ATTLIST weave xlintfile CDATA #IMPLIED >

   <!ELEMENT file EMPTY>
   <!ATTLIST file deletefile CDATA #IMPLIED >
   <!ATTLIST file renamefrom CDATA #IMPLIED >
   <!ATTLIST file renameto CDATA #IMPLIED >

   <!ELEMENT ant (stdout*,stderr*)>
   <!ATTLIST ant file CDATA #IMPLIED >
   <!ATTLIST ant target CDATA #IMPLIED >
   <!ATTLIST ant verbose CDATA #IMPLIED >

   <!ELEMENT comment (#PCDATA)>

=== eclipse-aspectj/aspectj/tests/src/test/java/org/aspectj/systemtest/ajc171/ajc171.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>

	<ajc-test dir="bugs171/pr384401" title="npe">
      <compile files="X.java" options="-1.5">
      	<message kind="error" line="9" text="the advice annotation must specify a pointcut value"/>
      </compile>
    </ajc-test>

	<ajc-test dir="bugs171/pr387444" title="soft 17">
      <compile files="Code.java" options="-1.7"/>
    </ajc-test>

	<ajc-test dir="bugs171/pr387444" title="soft 17 2">
      <compile files="Code2.java" options="-1.7"/>
      <run class="Code2">
        <stdout>
          <line text="foo"/>
        </stdout>
      </run>
    </ajc-test>

	<ajc-test dir="bugs171/pr387568" title="unresolvable enum">
      <compile files="Color.java Code.java" options="-1.5"/>
    </ajc-test>

    <ajc-test dir="bugs171/pr386049" title="itd abstract">
      <compile files="de/scrum_master/galileo/filter/BasicFilter.java de/scrum_master/galileo/filter/JsoupFilter.java de/scrum_master/galileo/LoggingAspect.aj" options="-1.5"/>
      <run class="de.scrum_master.galileo.filter.JsoupFilter">
        <stdout>
          <line text="JsoupFilter.getLogMessage()"/>
          <line text="run()"/>
        </stdout>
      </run>
    </ajc-test>

    <ajc-test dir="bugs171/pr73507" title="public ITDfs - 1">
      <compile files="Case1.java" options="-1.5"/>
      <run class="Case1">
        <stdout>
          <line text="Found a field called i"/>
        </stdout>
      </run>
    </ajc-test>
    
    <ajc-test dir="bugs171/pr73507" title="public ITDfs - 2">
      <compile files="Case2.java" options="-1.5"/>
      <run class="Case2">
        <stdout>
          <line text="Value of C.i is 1"/>
        </stdout>
      </run>
    </ajc-test>
    
     <ajc-test dir="bugs171/pr73507" title="public ITDfs - 3">
      <compile files="Case3.java" options="-1.5"/>
      <run class="Case3">
        <stdout>
          <line text="Value of C.i is 1"/>
          <line text="Value of C.j is 1"/>
          <line text="Value of C.k is 5"/>
          <line text="Value of I.i is 1"/>
          <line text="Value of I.j is 1"/>
        </stdout>
      </run>
    </ajc-test>
    
     <ajc-test dir="bugs171/pr73507" title="public ITDfs - 4">
      <compile files="Case4.java" options="-1.5">
        <message kind="error" line="13" text="can't override java.lang.String I.i with int C.i return types don't match"/>
      </compile>
    </ajc-test>
    
    <ajc-test dir="bugs171/pr73507" title="public ITDfs - 5">
      <compile files="Case5.java" options="-1.5"/>
      <run class="Case5">
        <stdout>
          <line text="public java.lang.String C.str"/>
        </stdout>
      </run>
    </ajc-test>
	
	<ajc-test dir="bugs171/pr384398" title="generics itds">
		<compile files="A.java B.java BAspect.aj" options="-1.5">
		<!-- 
			<message kind="weave" text="Join point 'constructor-call(void java.util.LinkedList.&lt;init&gt;())' in Type 'Foo' (Foo.java:41) advised by around advice from 'Bar' (Foo.java:14)"/>
		-->
		</compile>
		<!-- 
		<run class="Foo">
			<stdout>
				<line text="superaspect getNumber returns -2"/>
				<line text="Bar.method() running"/>
				<line text="abstract method returns []"/>
			</stdout>
		</run> -->
	</ajc-test>
	
	<ajc-test dir="bugs171/pr384398_2" title="generics itds 2">
		<compile files="A.java B.java BAspect.aj" options="-1.5">
		<!-- 
			<message kind="weave" text="Join point 'constructor-call(void java.util.LinkedList.&lt;init&gt;())' in Type 'Foo' (Foo.java:41) advised by around advice from 'Bar' (Foo.java:14)"/>
		-->
		</compile>
		<!-- 
		<run class="Foo">
			<stdout>
				<line text="superaspect getNumber returns -2"/>
				<line text="Bar.method() running"/>
				<line text="abstract method returns []"/>
			</stdout>
		</run> -->
	</ajc-test>
   
</suite>

=== eclipse-aspectj/aspectj/tests/src/test/resources/org/aspectj/systemtest/ajc196/sanity-tests-14.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>

    <!-- empty class -->
    <ajc-test dir="bugs160/simplejava" title="simple - a">
      <compile files="SimpleA.java" options="-14"/>
    </ajc-test>

    <!-- class with one method -->
    <ajc-test dir="bugs160/simplejava" title="simple - b">
      <compile files="SimpleB.java" options="-14"/>
      <run class="SimpleB"/>
    </ajc-test>
    
    <!-- empty aspect -->
    <ajc-test dir="bugs160/simplejava" title="simple - c">
      <compile files="SimpleC.java" options="-13"/>
    </ajc-test>
    
    <!-- simple before -->
    <ajc-test dir="bugs160/simplejava" title="simple - d">
      <compile files="SimpleD.java" options="-14"/>
    </ajc-test>
    
    <!-- simple itd field -->
    <ajc-test dir="bugs160/simplejava" title="simple - e">
      <compile files="SimpleE.java" options="-14"/>
    </ajc-test>
    
    <!-- aspect with main calling a static method -->
    <ajc-test dir="bugs160/simplejava" title="simple - f">
      <compile files="SimpleF.java" options="-14"/>
    </ajc-test>
    
    <!-- pertarget -->
    <ajc-test dir="bugs160/simplejava" title="simple - g">
      <compile files="SimpleG.java" options="-14"/>
    </ajc-test>
    
    <!-- generic ctor itds -->
    <ajc-test dir="bugs160/simplejava" title="simple - h">
      <compile files="SimpleH.java" options="-14"/>
    </ajc-test>
    
    <!-- overriding generic itd methods -->
    <ajc-test dir="bugs160/simplejava" title="simple - i">
      <compile files="SimpleI.java" options="-14"/>
    </ajc-test>
    
    <!-- check class file version is 57.0 -->
    <ajc-test dir="bugs160/simplejava" title="simple - j">
      <compile files="SimpleJ.java" options="-14"/>
    </ajc-test>

    <!-- check class file version is 57.0 -->
    <ajc-test dir="bugs160/simplejava" title="simple - k">
      <compile files="SimpleJ.java" options="-source 14"/>
    </ajc-test>

    <!-- check class file version is 49.0 -->
    <ajc-test dir="bugs160/simplejava" title="simple - m">
      <compile files="SimpleJ.java" options="-1.5"/>
    </ajc-test>

    <ajc-test dir="bugs160/simplejava" title="simple - n">
      <compile files="SimpleN.java" options="-14"/>
    </ajc-test>
</suite>

=== eclipse-aspectj/aspectj/tests/src/test/resources/org/aspectj/systemtest/ajc1923/ajc1923.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!--
	JDK 23 (https://openjdk.org/projects/jdk/23/):
		455:	Primitive Types in Patterns, instanceof, and switch (Preview)
		466:	Class-File API (Second Preview)
		467:	Markdown Documentation Comments
		469:	Vector API (Eighth Incubator)
		473:	Stream Gatherers (Second Preview)
		471:	Deprecate the Memory-Access Methods in sun.misc.Unsafe for Removal
		474:	ZGC: Generational Mode by Default
		476:	Module Import Declarations (Preview)
		477:	Implicitly Declared Classes and Instance Main Methods (Third Preview)
		480:	Structured Concurrency (Third Preview)
		481:	Scoped Values (Third Preview)
		482:	Flexible Constructor Bodies (Second Preview)
-->
<suite>

	<!-- https://openjdk.org/jeps/455 -->
	<ajc-test dir="features1923/java23" vm="23" title="primitive types patterns - switch">
		<compile files="PrimitivePatternsSwitch1.java" options="--enable-preview -23"/>
		<run class="PrimitivePatternsSwitch1" vmargs="--enable-preview">
			<stdout>
			<line text="one"/>
			<line text="two"/>
			<line text="many"/>
			<line text="lots"/>
			</stdout>
		</run>
	</ajc-test>
	
	<ajc-test dir="bugs1923/gh328" vm="17" title="problem with inline accessor generator for around advice">
		<compile files="One.java" options="-17">
		</compile>
	</ajc-test>
	
	<ajc-test dir="bugs1923/gh327" vm="17" title="problem with intertype field declaration code generation - static">
		<compile files="A.aj" options="-17">
		</compile>
	</ajc-test>
	
	<ajc-test dir="bugs1923/gh327" vm="17" title="problem with intertype field declaration code generation - nonstatic">
		<compile files="B.aj" options="-17">
		</compile>
	</ajc-test>

    <ajc-test dir="new/verifyError" pr="36673"
      title="problem with intertype field declaration code generation - private">
        <compile files="Privilege.java" options="-17"/>
        <run class="Privilege"/>
    </ajc-test>

	<ajc-test dir="bugs1923/gh327" vm="17" title="problem with intertype method declaration code generation">
		<compile files="F.aj" options="-17">
		</compile>
	</ajc-test>

	<ajc-test dir="bugs1923/gh326" vm="17" title="classcast on exception handling aspect">
		<compile files="pkg/BusinessDao.java pkg/BusinessService.java pkg/SourceException.java pkg/TargetException.java pkg/BusinessDto.java pkg/HandleSourceException.java pkg/SourceExceptionHandlerAspect.aj" options="-17">
		</compile>
		<run class="pkg.BusinessService">
		<stdout>
		<line text="42"/>
		</stdout>
		</run>
	</ajc-test>

	<ajc-test dir="bugs1923/gh322" vm="17" title="ajc error for particular Pointcut and @Deprecated">
		<!--
		<compile files="TheClass.java TheInterface.java TheAspect.java SomeAnnotation.java" options="-17,-Xlint:ignore">
		</compile>
		<compile files="TheInterface.java TheAspect.java SomeAnnotation.java TheClass.java" options="-17,-Xlint:ignore">
		</compile>
		-->
		<compile files="TheAspect.java SomeAnnotation.java TheClass.java TheInterface.java " options="-17,-Xlint:ignore">
		</compile>
		<compile files="TheAspect.java SomeAnnotation.java TheClass.java TheInterface.java" options="-17,-Xlint:ignore">
		</compile>
	</ajc-test>



</suite>

=== eclipse-aspectj/aspectj/tests/src/org/aspectj/systemtest/ajc150/ataspectj/annotationgen.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>
<!-- @AspectJ v1.5.0 Tests -->

    <!-- ================================================================= -->
    <!-- Adrian's tests for generation of @AspectJ annotations from ajc                                   -->
    <!-- ================================================================= -->

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for simple aspect">
        <compile files="SimpleAspect.aj" options="-1.5"/>
        <run class="SimpleAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for simple annotated aspect">
        <compile files="SimpleAnnotatedAspect.aj" options="-1.5"/>
        <run class="SimpleAnnotatedAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for simple aspect pre 1.5">
        <compile files="Simple14Aspect.aj" options="-1.4"/>
        <compile files="Simple14AspectTest.java" options="-1.5"/>
        <run class="Simple14AspectTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for privileged aspect">
        <compile files="PrivilegedAspect.aj" options="-1.5"/>
        <run class="PrivilegedAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for perthis aspect">
        <compile files="PerThisAspect.aj" options="-1.5"/>
        <run class="PerThisAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for pertarget aspect">
        <compile files="PerTargetAspect.aj" options="-1.5"/>
        <run class="PerTargetAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for percflow aspect">
        <compile files="PerCflowAspect.aj" options="-1.5"/>
        <run class="PerCflowAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for percflowbelow aspect">
        <compile files="PerCflowbelowAspect.aj" options="-1.5"/>
        <run class="PerCflowbelowAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for pertypewithin aspect">
        <compile files="PerTypeWithinAspect.aj" options="-1.5"/>
        <run class="PerTypeWithinAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for inner aspect of aspect">
        <compile files="InnerAspectAspect.aj" options="-1.5"/>
        <run class="InnerAspectAspect"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for inner aspect of class">
        <compile files="InnerAspectClass.aj" options="-1.5"/>
        <run class="InnerAspectClass"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for advice declarations">
        <compile files="BasicAdvice.aj" options="-1.5"/>
        <run class="BasicAdvice"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for simple pointcut">
        <compile files="SimplePointcut.aj" options="-1.5"/>
        <run class="SimplePointcut"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for pointcut modifiers">
        <compile files="PointcutModifiers.aj" options="-1.5"/>
        <run class="PointcutModifiers"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for pointcut params">
        <compile files="PointcutsWithParams.aj" options="-1.5"/>
        <run class="PointcutsWithParams"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="annotation gen for pointcut refs">
        <compile files="ReferencePointcuts.aj" options="-1.5"/>
        <run class="ReferencePointcuts"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="before ann with non-void return">
        <compile files="BeforeWithBadReturn.java" options="-1.5">
            <message kind="error" line="7" text="This advice must return void"/>
            <message kind="error" line="7" text="This method must return a result of type String"/>
        </compile>
    </ajc-test>

     <ajc-test dir="java5/ataspectj/annotationGen" title="two anns on same element">
        <compile files="TwoForThePriceOfOne.java" options="-1.5">
            <message kind="error" line="7" text="The annotation @Pointcut is disallowed for this location"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="bad pcut in after advice">
        <compile files="AfterReturningWithBadPCut.java" options="-1.5">
            <message kind="error" line="6" text="Syntax error on token &quot;excution(* *.*(..))&quot;"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="bad parameter binding in advice">
        <compile files="BadParameterBinding.java" options="-1.5">
            <message kind="warning" line="11" text="no match for this type name: bpb"/>
            <message kind="warning" line="15" text="no match for this type name: TheUnknownType"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="simple pointcut no params">
        <compile files="APointcut.java" options="-1.5"/>
        <run class="APointcut"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="pointcut medley">
        <compile files="PointcutAssortment.java" options="-1.5">
            <message kind="error" line="9" text="Methods annotated with @Pointcut must return void"/>
            <message kind="error" line="9" text="This method must return a result of type String"/>
            <message kind="error" line="15" text="Pointcuts without an if() expression should have an empty method body"/>
            <message kind="error" line="28" text="Duplicate annotation @Pointcut"/>
            <message kind="error" line="29" text="Duplicate annotation @Pointcut"/>
            <message kind="error" line="11" text="can't find referenced pointcut foo"/>
            <message kind="warning" line="32" text="no match for this type name: foo [Xlint:invalidAbsoluteTypeName]"/>
         </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/annotationGen" title="advice in a class">
        <compile files="AdviceInAClass.java" options="-1.5">
            <message kind="error" line="6" text="Advice must be declared inside an aspect type"/>
        </compile>
    </ajc-test>

   <ajc-test dir="java5/ataspectj/annotationGen" title="ann gen for deows">
        <compile files="Deow.aj" options="-1.5">
        </compile>
        <run class="Deow"/>
    </ajc-test>          

   <ajc-test dir="java5/ataspectj/annotationGen" title="runtime pointcut resolution referencing compiled pointcuts">
        <compile files="PCLib.aj,RuntimePointcuts.java" options="-1.5">
        </compile>
        <run class="RuntimePointcuts" classpath=".;../lib/bcel/bcel.jar" ltw=""/>
    </ajc-test>          

   <ajc-test dir="java5/ataspectj/annotationGen" title="ann gen for decp">
        <compile files="DeclareParentsTest.aj" options="-1.5, -outxml">
        </compile>
        <run class="DeclareParentsTest" ltw=""/>
    </ajc-test>          
    
      <ajc-test dir="java5/ataspectj/annotationGen" title="ann gen for decp 2">
        <compile files="DeclareParentsTestAdvanced.aj" options="-1.5, -outxml">
        </compile>
        <run class="a.b.c.DeclareParentsTestAdvanced" ltw=""/>
    </ajc-test>
    
    <ajc-test dir="java5/ataspectj/annotationGen" title="ann gen for decs">
        <compile files="DeclareSoftTest.aj" options="-1.5">
        </compile>
        <run class="DeclareSoftTest"/>
    </ajc-test>     
    
    <ajc-test dir="java5/ataspectj/annotationGen" title="ann gen for dec precedence">
        <compile files="DeclarePrecedenceTest.aj" options="-1.5">
        </compile>
        <run class="DeclarePrecedenceTest"/>
    </ajc-test>     
    
     <ajc-test dir="java5/ataspectj/annotationGen" title="ann gen for dec annotation">
        <compile files="DeclareAnnotationTest.aj" options="-1.5">
        </compile>
        <run class="DeclareAnnotationTest"/>
    </ajc-test>
    
    <ajc-test dir="java5/ataspectj/annotationGen" title="ann gen for itds">
        <compile files="ITDTest.aj" options="-1.5, -outxml -Xlint:ignore -makeAjReflectable">
        </compile>
        <run class="a.b.c.ITDTest" ltw=""/>
    </ajc-test>    
</suite>

=== eclipse-aspectj/aspectj/tests/src/org/aspectj/systemtest/ajc160/newfeatures-tests.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.6.0 Tests -->
<suite>

    <ajc-test dir="features160/weavingJavaxPackage" title="weave javax classes - no">
      <compile files="A.java B.java" />
      <compile files="X.aj" outjar="code.jar" options="-1.4"/>
      <run class="javax.foo.A" classpath="code.jar" ltw="aop1.xml">
      <stderr>
      <line text="AspectJ Weaver Version"/>
      <line text="register classloader"/>
      <line text="using configuration"/>
      <line text="register aspect X"/>
      <line text="not being woven"/>
      </stderr>
        <stdout>
           <line text="(A) method running"/>
           <line text="(B) method running"/>
        </stdout>
      </run>
    </ajc-test>
    
    <ajc-test dir="features160/weavingJavaxPackage" title="weave javax classes - yes">
      <compile files="A.java B.java" />
      <compile files="X.aj" outjar="code.jar" options="-1.4"/>
      <run class="javax.foo.A" classpath="code.jar" ltw="aop2.xml">
        <stdout>
           <line text="advised"/>
           <line text="(A) method running"/>
           <line text="advised"/>
           <line text="(B) method running"/>
        </stdout>
      </run>
    </ajc-test>

</suite>

=== eclipse-aspectj/aspectj/tests/src/test/resources/org/aspectj/systemtest/design/design.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd" []>
<!-- Language Design Tests -->
<suite>
    <ajc-test dir="design/intro"
      title="initial tests for new introduction style" keywords="from-design">
        <compile files="Simple.java"/>
        <run class="Simple"/>
    </ajc-test>

    <ajc-test dir="design/intro"
      title="overriding of introduced methods and accessibility"
      keywords="from-design">
        <compile files="Overriding.java"/>
        <run class="Overriding"/>
    </ajc-test>

    <ajc-test dir="design/intro"
      title="within and introductions behaves correctly" keywords="from-design">
        <compile files="Within.java" options="-1.4"/>
        <run class="Within"/>
    </ajc-test>

    <ajc-test dir="design/intro" pr="570"
      title="correct inheritance of multiple concrete methods"
      keywords="from-design">
        <compile files="MultiInheritCP.java"/>
        <run class="MultiInheritCP"/>
    </ajc-test>

    <ajc-test dir="design/intro" pr="570"
      title="errors in inheritance of multiple concrete methods"
      keywords="from-design">
        <compile files="MultiInheritCF.java">
<!-- the error is:       error at java\lang\Object.java::0 can't override int I2.toString() with java.lang.String java.lang.Object.toString() return types don't match-->
			<message kind="error" line="0"/>
			<message kind="error" line="17"/>
			<message kind="error" line="18"/>
            <message kind="error" line="21"/>
            <message kind="error" line="41"/>
            <message kind="error" line="42"/>
            <message kind="error" line="43"/>
            <message kind="error" line="45"/>
            <message kind="error" line="46"/>
        </compile>
    </ajc-test>

    <ajc-test dir="design/intro"
      title="declared exceptions are checked correctly on intros (errors)">
        <compile files="ExceptionsCF.java">
            <message kind="error" line="8"/>
            <message kind="error" line="23"/>
        </compile>
    </ajc-test>

    <ajc-test dir="design/intro"
      title="declared exceptions are checked correctly on intros">
      <compile files="ExceptionsCP.java">
      </compile>
        <run class="ExceptionsCP"/>
    </ajc-test>

    <ajc-test dir="design/reflect"
      title="Joinpoint is not created for foo(String) when before() advice is present."
      keywords="from-design">
        <compile files="SimpleAround1.java"/>
        <run class="SimpleAround1"/>
    </ajc-test>

    <ajc-test dir="design/eachobject"
      title="more tests of eachobject with some difficult typing issues"
      keywords="from-design">
        <compile files="Tricky3.java" options="-1.4"/>
        <run class="Tricky3"/>
    </ajc-test>

    <ajc-test dir="design/eachobject"
      title="eachobject: eachobject(receptions(...)) [eachobject]"
      keywords="from-design">
        <compile files="Tricky1.java"/>
        <run class="Tricky1"/>
    </ajc-test>

    <ajc-test dir="design/reflect" title="Checking new joinpoints"
      keywords="from-design">
        <compile files="Coverage.java" options="-Xlint:ignore"/>
        <run class="Coverage"/>
    </ajc-test>

    <ajc-test dir="design/eachobject"
      title="eachobject: simple test [eachobject] (still)"
      keywords="from-design">
        <compile files="Simple.java"/>
        <run class="Simple"/>
    </ajc-test>

    <ajc-test dir="design/intro"
      title="scope issues with introduction (needs more work)"
      keywords="from-design">
        <compile files="p1/ScopeIssues.java,p1/C1.java"/>
        <run class="p1.ScopeIssues"/>
    </ajc-test>

<!-- uncomment this test if we decide to implement 42743 
	<ajc-test dir="design/soft" pr="42743"
		title="declare soft limitation">
		<compile files="DeclareSoft.aj"/>
		<run class="DeclareSoft"/>
	</ajc-test>
-->


</suite>
